### ISSUE TITLE
fixture doesn't match for getData/getListData when using query parameters

### ISSUE THREAD

**Issue by pmgmendes** [canjs/can-fixture#115]
It seems that can-fixture is not able to match the requests for getData/getListData when the url has query 
parameters. The test bellow passes if the fixture is declared without any query parameters like e.g.
```
fixture("GET /todos/A", {id: "A"});
```
This issue makes it hard to provide multiple fixtures to be used in a given model under test.
fixtures with query params for updateData/createData testing work as expected. 

Related to the donejs topic [Can-connect models and HATEOAS](http://forums.donejs.com/t/can-connect-models-and-hateoas/648).

I've setup a jsbin @ https://jsbin.com/koqebe/10/edit?js,output but its not working due an error within one of the baseMap's behavior. Not sure what's the cause. Here's the code.

### test.js
```
var DefineMap = require("can-define/map/map");
var DefineList = require("can-define/list/list");
var connect = require("can-connect");
var baseMap = require("can-connect/can/base-map/");
var set = require("can-set");
var QUnit = require("steal-qunit");
var fixture = require("can-fixture");

const Todo = DefineMap.extend({
  id: "string"
});

Todo.List = DefineList.extend({
  "#": Todo
});

Todo.algebra = new set.Algebra(set.props.id("id"));

Todo.connection = baseMap({
  Map: Todo,
  List: Todo.List,
  url: {
    getData: "GET /todos/{id}"
  }
});

QUnit.module("Todo module");

QUnit.test("fixture doesn't match for getData/getListData when using query parameters", function(assert) {

  fixture("GET /todos/A?complete=true", {id: "A"});

  let done = assert.async();
  Todo.get({id: "A", complete: true}).then(todo => {
    assert.equal(todo.id, "A");
    done();
  });

});
```

### test.html
```
<title>fixture doesn't match for getData/getListData when using query parameters</title>
<script src="../../../../../../node_modules/steal/steal.js" main="test"></script>
<div id="qunit-fixture"></div>
```

**Comment by andrejewski** [comment]
Hello @pmgmendes, yes currently query strings are not supported in that syntax. This limitation is documented in [`can-fixture > ajaxSettings > options > url`](https://canjs.com/doc/can-fixture/types/ajaxSettings.html). I have reworked your JSBin to give you what I understood to be the expected behavior: https://jsbin.com/daqaroboni/edit?js,output. Please let me know if your feature is desired or the given alternative syntaxes are adequate. We can have some dicussion on whether this is something worth adding if you wish.

**Comment by pmgmendes** [comment]
Hi @andrejewski!
Yes, your alternative does the trick for me. I wasn't aware of the limitation. 
Still, I give it a spin with the fixture initialization described in the linked doc page but with no success.
```
fixture({
  method: "GET", 
  url: "/todos/{id}", 
  data: {id: "A", complete: true} // if "data" is removed, it works
}, function(req, res) {
  return {id: "A", complete: true}
});
```
It works only if "data" is removed.

I guess this enhancement would make sense at least for fixtures with data sets targeting getListData interface implementations.

Thanks for the help. I'm closing the issue.

**Comment by justinbmeyer** [comment]
I think this would still be a nice feature.  I think people expect those sorts of urls to work.  We could probably make this happen.

**Comment by pmgmendes** [comment]
Recently I've came back to this issue and the `fixture(ajaxSettings, data)` is working as expected. This means can-fixture is able to differentiate two fixtures with the same url based od the provided data (query parameters).
`fixture({url: /todos", data: { queryParam1: "A"} }, {})`


I think
