### ISSUE TITLE
FormData and other xhr send types are converted to plain objects

### ISSUE THREAD

**Issue by green3g** [canjs/can-fixture#133]
FormData is a valid option for xhr requests and is useful for uploading files. In addition there are other types, like Blob that may be sent via xhr. https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/send

If I have an xhr request like this:

```javascript
        const data = new FormData();
        for (let i = 0; i < files.length; i++) {
            data.append(i, files.item(i));
        }

            const req = new XMLHttpRequest();
            req.open('POST', this.properties.url, true);
            req.onload = function () {
                if (req.status === 200) {
                    resolve(JSON.parse(req.responseText));
                } else {
                    reject(req);
                }
            };
            req.onerror = reject;
            req.send(data);
```

The fixture `request` variable does not allow accessing the FormData properties and fails with 
```
// throws error TypeError: 'entries' called on an object that does not implement interface FormData.
```

The solution is something like checking to see of the data is an instance of the various data types that can be passed to `send`. Will submit a pr to demonstrate.

**Comment by chasenlehara** [comment]
This should be fixed in [1.2.2](https://github.com/canjs/can-fixture/releases/tag/v1.2.2). Thanks @roemhildtg!
