### ISSUE TITLE
Make can-fixture loadable via script tag

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-fixture#22]
I'm thinking there should be a:
- can-fixture.js - does the basic fixture stuff
- can-fixture-store.js - adds the store, has its own memory cache / set stuff

@matthewp I might need to make some changes to steal-tools to make `can-fixture-store.js` possible, maybe not.  I want to make sure there can be no conflicts if someone also has loaded `can-connect` via a script tag.

Perhaps the solution is for a special mapping during the build, to alias `can-connect` as something else?  Do you think this could work?  Thanks.

**Comment by matthewp** [comment]
I don't quite follow, what sort of conflicts are you concerned about?
