### ISSUE TITLE
adding a store with `METHOD` doesn't make sense

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-fixture#30]
`fixture("GET /todos/{id}", store)` causes strange behavior.

**Comment by andrejewski** [comment]
Clarifying: a call to `fixture('GET /models/{id}', store.getData);` is the proper way to apply this fixture and we should add an error if fixture is called with a non-function (e.g. `store`)? Or does fixture accept objects so we should warn about `store` being store-like?

**Comment by justinbmeyer** [comment]
`fixture("/todos/{id}", store)` is the right way to call with a store.  It shouldn't have a `get` because this is going to setup a `POST /todos`, `GET /todos`, `PUT /todos/{id}`, `GET /todos/{id}`, `DELETE /todos/{id}`.


Normally the 1st argument is converted to an [ajaxSettings](http://canjs.com/doc/can-fixture/types/ajaxSettings.html) object.  That happens if it's a string around here:

https://github.com/canjs/can-fixture/blob/master/core.js#L40


This fix should probably change should probably make it so that `ajaxSettings` conversion always happens.  Then, if there's a `method`, we should probably give people a warning.
