### ISSUE TITLE
Including can-fixture changes content-type in ajax requests

### ISSUE THREAD

**Issue by julia-allyce** [canjs/can-fixture#31]
I noticed that including can-fixture removes the content-type from empty  $.ajax() requests, and changes it to `text/plain;charset=UTF-8` for those with data.

here is a gist of some simple test code. I just commented/uncommented the fixture script tag to test:
https://gist.github.com/julia-allyce/d02941eea17edcca76f765aaf573abdc

With can-fixture there is no content type.
<img width="1116" alt="with can-fixture" src="https://cloud.githubusercontent.com/assets/1000574/14927361/4f896674-0e1f-11e6-9b92-f0b517f2377c.png">
Without can-fixture the content type is set as expected.
<img width="1118" alt="no-fixtures" src="https://cloud.githubusercontent.com/assets/1000574/14927363/526c1490-0e1f-11e6-8a44-d9163e7df46f.png">

if you include data in your request, the content-type is set to `text/plain;charset=UTF-8`

**Comment by justinbmeyer** [comment]
Thanks for reporting!

**Comment by julia-allyce** [comment]
@justinbmeyer  any update on this? If its a simple fix and you can point me in the right direction, I'll make the PR.

**Comment by justinbmeyer** [comment]
Does `_headers` here: https://github.com/canjs/can-fixture/blob/master/xhr.js#L163 have the content type?

If yes, I think the problem is that they aren't set on the `xhr` object created here: https://github.com/canjs/can-fixture/blob/master/xhr.js#L60

**Comment by BigAB** [comment]
Just chiming in here, I believe this is causing a problem on one of our projects. Currently we have to **comment out** our fixtures import instead of turing them off (`fixture.on = false;`), or else there are problems when we connect to the real api

**Comment by BigAB** [comment]
Adding another point, just importing `can-fixture` breaks [Axios](https://github.com/mzabriskie/axios)

all requests break with error:

```
Uncaught TypeError: headers.split is not a function
```

**Comment by BigAB** [comment]
https://github.com/canjs/can-fixture/blob/master/xhr.js#L108

The method `getAllResponseHeaders()` should be returning a string, yet we return an object, this is why axios breaks.
https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/getAllResponseHeaders

Also our `getResponseHeader()` implementation seems to return an empty string for any key
https://github.com/canjs/can-fixture/blob/master/xhr.js#L146

**Comment by bmomberger-bitovi** [comment]
#39 should have fixed this issue.
