### ISSUE TITLE
Examples not working on latest from npm

### ISSUE THREAD

**Issue by BigAB** [canjs/can-fixture#35]
The install from npm currently gives the version `0.4.0-pre.2`.

With that version the first  [**"Basic Use"**](https://github.com/canjs/can-fixture#basic-use) example from the README does not work:

``` javascript
fixture({url: "/service", method: "get"}, function(request, response){
  response({message: "Hello World"});
})
```

This appears to be because method does not match a subset, or something, because if I change `method` to `type` (the XHR property `method` like method) then it starts to work

``` javascript
fixture({url: "/service", type: "get"}, function(request, response){
  response({message: "Hello World"});
})
```

Not sure if the fix should be updating the docs or treating method as a special value.

**Comment by justinbmeyer** [comment]
Updating the docs. The example is an old one that worked against the jquery version.

**Comment by ccummings** [comment]
So are you suggesting we change mentions of `method` to `type`?

`type` is a jquery thing whereas `method` is what the XHR spec uses. 

I think we should keep the docs as is and just make method and type work.
