### ISSUE TITLE
ID detection doesn't work for MongoDB / hexadecimal ID's

### ISSUE THREAD

**Issue by Bajix** [canjs/can-fixture#44]
The getId functionality assumes that the ID prop is `id` and relies on fallback approaches if that's not the case. The fallback approach doesn't identify hexadecimal ID's, and so currently MongoDB users using `_id` instead of id, with hexadecimal ID's instead of base 10 ID's, will get 404's.

**Comment by justinbmeyer** [comment]
It seems like you are using the legacyStore with is deprecated (and not documented on can-fixture). Can you switch to the algebra based stores which shouldn't have this problem: https://github.com/canjs/can-fixture#fixturestorebaseitems-algebra

**Comment by Bajix** [comment]
I already was.

```
var users = require('@acme/fixtures').users,
  fixture = require('can-fixture'),
  set = require('can-set');

var algebra = new set.Algebra(
  set.comparators.id('_id'),
  set.comparators.boolean('provisional')
);

var store = fixture.store(users, algebra);

fixture({
  'GET /users': store.findAll,
  'GET /users/{_id}': store.findOne,
  'POST /users': store.create,
  'PUT /users/{_id}': store.update,
  'DELETE /users/{_id}': store.destroy
});

module.exports = store;
```

**Comment by justinbmeyer** [comment]
I'm not sure how getId is being used then.  Which getId are you referring to? Afaik, only the legacy store uses it: https://github.com/canjs/can-fixture/blob/master/helpers/legacyStore.js#L1

**Comment by justinbmeyer** [comment]
Can you submit a test to show this breaking?

**Comment by Bajix** [comment]
Sure

**Comment by Bajix** [comment]
Ok the new store works, the issue is in fact that it's loading the legacy store instead of the new store.

https://github.com/canjs/can-fixture/blob/master/store.js#L115

```
Store.make = function (count, make, algebra) {
    /*jshint eqeqeq:false */
    // check if algebra was passed
    var isNew = false;
    if( count instanceof canSet.Algebra || make instanceof canSet.Algebra || algebra instanceof canSet.Algebra ) {
        isNew = true;
    }
    if(!isNew) {
        return legacyStore.apply(this, arguments);
    }
```

That isNew check fails for me because my can-set !== can-fixture's can-set

**Comment by Bajix** [comment]
Yay dependency traps! My original npm install had setup 0.4.0-pre.2 rather than 0.3.0. Subsequently can-fixture was loading it's own version, can-set@0.6.0-pre.3, rather than my installed version, can-set@0.5.6. The instanceof check then would fail, thus reverting to legacyStore.

I think @matthewp had already fixed this, at least he did with can-connect, but I suspect your tags were off, making npm install default install pre-release versions.

It's a design flaw for this to break by simply passing in a different can-set version.

**Comment by Bajix** [comment]
Also, wasn't npmAlgorithm: flat suppose to prevent this kind of thing from happening?

**Comment by justinbmeyer** [comment]
I think we're planning on adding a warning when this type of thing happens in steal.  `npmAlgorithm: flat` has nothing to do with it.  cc @matthewp
