### ISSUE TITLE
Slow mode test fails intermittently

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-fixture#79]
[This test](https://github.com/canjs/can-fixture/blob/7f29e115e4a76fa07cdf5bcda1f4966dfad4fb8e/test/fixture_test.js#L1410-L1428) fails intermittently in IE9 and iOS Safari. Here is an example of one of the failures: https://saucelabs.com/jobs/588c85e191cc43148be673673b521817.

**Comment by phillipskevin** [comment]
This test is still failing intermittently after changing the test to check that the delay is at least 1 second. Here is an example of a failed run: https://saucelabs.com/jobs/08214e3e71dd4eb7a0ddfeee735b15a3.

**Comment by phillipskevin** [comment]
Here is a failing run that shows what is happening: https://saucelabs.com/jobs/caa70e8c28f04147acf9cf4a03b44b7e

in IE 9, the `fixture({url: url}, 1000);` is called back in 998ms.

**Comment by justinbmeyer** [comment]
haha... How annoying.  ok, maybe just make sure it's around a second then.
