### ISSUE TITLE
Mock XHR returns incorrect response header

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-fixture#86]
Our mock XHR is [always returning ""](https://github.com/canjs/can-fixture/blob/master/xhr.js#L169-L171) from `getResponseHeader`.

Things that depend on this value (like socket.io) will not work correctly.

**Comment by phillipskevin** [comment]
This is the last piece of https://github.com/canjs/canjs/issues/2778. 

To determine this was the issue, I put the code below at the end of our XMLHttpRequest constructor function and compared the output of a working XHR with the failing XHR:

```js
return new Proxy(this, {
 get: function(target, prop) {
   var funcOrProp = target[prop];

   if (typeof funcOrProp === 'function') {
     return function() {
       var result = funcOrProp.apply(target, arguments);
       console.log(prop + '(' + [].join.call(arguments, ',') + ') -> ' + JSON.stringify(result));
       return result;
     }
   } else {
     console.log('GET', prop, '->', funcOrProp);
     return funcOrProp;
   }
 },
 set: function(target, prop, value) {
   console.log('SET', prop, 'to', value);
   target[prop] = value;
 }
});
```

Leaving the code here in case we run into more issues with our mock XHR in the future.

**Comment by matthewp** [comment]
Created this so we can track everything that's not going to be working right now: https://github.com/canjs/can-fixture/issues/87

**Comment by phillipskevin** [comment]
The test for this is failing in different browsers on sauce labs because the header's value is `"application/json; charset=utf-8"`.
